apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth-svc
  template:
    metadata:
      labels:
        app: user-auth-svc
    spec:
      containers:
      - name: user-auth-svc
        image: userauth.azurecr.io/samples/user-auth-repo:latest
        ports:
        - containerPort: 3008
---
apiVersion: v1
kind: Service
metadata:
  name: user-auth-svc
  namespace: default
  labels:
    app: user-auth-svc
spec:
  selector:
    app: user-auth-svc
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3008
  type: LoadBalancer
