Deployment:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth-svc
  template:
    metadata:
      labels:
        app: user-auth-svc
    spec:
      containers:
      - name: user-auth-svc
        image: 961341555113.dkr.ecr.us-east-1.amazonaws.com/user-auth:latest
        ports:
        - containerPort: 3008
---
apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  namespace: default
  labels:
    app: user-auth-service
spec:
  selector:
    app: user-auth-svc
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3008
  type: NodePort