apiVersion: v1
kind: Service
metadata:
    name: userauthazurecriosamplesuserauthrepo
spec:
    type: LoadBalancer
    ports:
    - port: 3008 
    selector:
        app: userauthazurecriosamplesuserauthrepo